customers = [
    {"id": "cust_01", "name": "Ali Raza", "email": "ali.raza@example.com", "tier": "free"},
    {"id": "cust_02", "name": "Sara Khan", "email": "sara.khan@example.com", "tier": "premium"},
    {"id": "cust_03", "name": "Bilal Ahmed", "email": "bilal.ahmed@example.com", "tier": "free"},
    {"id": "cust_04", "name": "Ayesha Malik", "email": "ayesha.malik@example.com", "tier": "premium"},
    {"id": "cust_05", "name": "Usman Tariq", "email": "usman.tariq@example.com", "tier": "free"},
    {"id": "cust_06", "name": "Fatima Noor", "email": "fatima.noor@example.com", "tier": "premium"},
    {"id": "cust_07", "name": "Hamza Sheikh", "email": "hamza.sheikh@example.com", "tier": "free"},
    {"id": "cust_08", "name": "Zara Iqbal", "email": "zara.iqbal@example.com", "tier": "free"},
    {"id": "cust_09", "name": "Omar Farooq", "email": "omar.farooq@example.com", "tier": "premium"},
    {"id": "cust_10", "name": "Mahnoor Aslam", "email": "mahnoor.aslam@example.com", "tier": "free"},
    {"id": "cust_11", "name": "Danish Qureshi", "email": "danish.qureshi@example.com", "tier": "premium"},
    {"id": "cust_12", "name": "Sana Yousaf", "email": "sana.yousaf@example.com", "tier": "free"},
    {"id": "cust_13", "name": "Kashif Rana", "email": "kashif.rana@example.com", "tier": "free"},
    {"id": "cust_14", "name": "Nida Aziz", "email": "nida.aziz@example.com", "tier": "premium"},
    {"id": "cust_15", "name": "Waqas Anjum", "email": "waqas.anjum@example.com", "tier": "free"},
]

orders = [
    {"id": "ord_001", "customer_id": "cust_01", "items": ["Wireless Mouse"], "status": "delivered", "total": 25, "created_at": "2026-06-01"},
    {"id": "ord_002", "customer_id": "cust_01", "items": ["Keyboard"], "status": "pending", "total": 45, "created_at": "2026-08-10"},
    {"id": "ord_003", "customer_id": "cust_02", "items": ["Laptop Stand", "USB Hub"], "status": "delivered", "total": 60, "created_at": "2026-05-20"},
    {"id": "ord_004", "customer_id": "cust_03", "items": ["Monitor"], "status": "delivered", "total": 180, "created_at": "2026-07-15"},
    {"id": "ord_005", "customer_id": "cust_04", "items": ["Headphones"], "status": "delivered", "total": 90, "created_at": "2026-04-11"},
    {"id": "ord_006", "customer_id": "cust_04", "items": ["Webcam"], "status": "pending", "total": 55, "created_at": "2026-08-20"},
    {"id": "ord_007", "customer_id": "cust_05", "items": ["Desk Lamp"], "status": "delivered", "total": 30, "created_at": "2026-03-05"},
    {"id": "ord_008", "customer_id": "cust_06", "items": ["Office Chair"], "status": "delivered", "total": 220, "created_at": "2026-06-25"},
    {"id": "ord_009", "customer_id": "cust_06", "items": ["Mouse Pad"], "status": "delivered", "total": 12, "created_at": "2026-08-12"},
    {"id": "ord_010", "customer_id": "cust_07", "items": ["External SSD"], "status": "pending", "total": 95, "created_at": "2026-08-22"},
    {"id": "ord_011", "customer_id": "cust_08", "items": ["Router"], "status": "delivered", "total": 70, "created_at": "2026-02-14"},
    {"id": "ord_012", "customer_id": "cust_09", "items": ["Graphics Tablet"], "status": "delivered", "total": 150, "created_at": "2026-07-30"},
    {"id": "ord_013", "customer_id": "cust_10", "items": ["Phone Case"], "status": "delivered", "total": 15, "created_at": "2026-01-19"},
    {"id": "ord_014", "customer_id": "cust_10", "items": ["Charger"], "status": "pending", "total": 20, "created_at": "2026-08-24"},
    {"id": "ord_015", "customer_id": "cust_11", "items": ["Smartwatch"], "status": "delivered", "total": 130, "created_at": "2026-05-05"},
    {"id": "ord_016", "customer_id": "cust_12", "items": ["Bluetooth Speaker"], "status": "delivered", "total": 45, "created_at": "2026-06-18"},
    {"id": "ord_017", "customer_id": "cust_13", "items": ["Laptop Bag"], "status": "delivered", "total": 35, "created_at": "2026-03-22"},
    {"id": "ord_018", "customer_id": "cust_14", "items": ["Ring Light"], "status": "delivered", "total": 40, "created_at": "2026-07-02"},
    {"id": "ord_019", "customer_id": "cust_14", "items": ["Tripod"], "status": "pending", "total": 28, "created_at": "2026-08-23"},
    {"id": "ord_020", "customer_id": "cust_15", "items": ["Power Bank"], "status": "delivered", "total": 22, "created_at": "2026-04-28"},
]